apiVersion: v1
kind: Secret
metadata:
  name: rafa-secret
  namespace: rafa
type: Opaque
data:
  username: dXNlcm5hbWU=
  password: cGFzc3dvcmQ=
---
apiVersion: batch/v1
kind: Job
metadata:
  name: fake-job
  namespace: rafa
  labels:
    app: fake-job
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 3
  ttlSecondsAfterFinished: 100
  template:
    metadata:
      labels:
        app: fake-job
    spec:
      # serviceAccountName: "rafa-service-account"
      restartPolicy: Never
      containers:
      - name: fake-job-container
        image: rafaelbodao/fakejob:latest
        imagePullPolicy: Always
        env:
          - name: SECONDS_TO_SLEEP
            value: "5"
          - name: USER_NAME
            valueFrom:
              secretKeyRef:
                name: rafa-secret
                key: username
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: rafa-secret
                key: password
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        securityContext:
          runAsNonRoot: true
          runAsUser: 65534
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
